<?php $total = $block->_getCartTotal();
$threshold = $block->_getThreshold();
$markThres = floatval($total) > floatval($threshold) ? "&BigOnly" : "&LittleThings";
$markFlag = floatval($total) > floatval($threshold);
$cartSelector = $block->_getCartSeletor();

if (empty(trim($cartSelector))) {
    $cartSelector = '.page-title';
}

$markThres = $markThres.'&elements='.urlencode($cartSelector) ;

?>

<?php $country = $block->_getCountry(); ?>
<?php if ($country == 'AU') {
    $ec_pattern = sprintf("%s %s %s %s ", '<script src="https://widgets.shophumm.com.au/content/scripts/price-info.js?productPrice=', $total, $markThres, '"></script>');
}
if ($country == 'NZ') {
    if (!$markFlag) {
        $ec_pattern = sprintf("%s%s%s%s", '<script src= "https://widgets.shophumm.co.nz/content/scripts/price-info.js?productPrice=', $total, '&LittleThings&little=F5', '"></script>');
    }
}
 echo $ec_pattern;
?>



