<?php list($productPrice, $littleBig) = $block->_getProductPrice(); ?>
<?php $country = $block->_getCountry(); ?>
<?php $productSelector = $block->_getProductSeletor();

if (empty(trim($productSelector))) {
    $productSelector = '.product-info-price';
}
?>

<?php if ($country == 'AU') : ?>
    <?php if (!$littleBig) : ?>
        <script src="https://widgets.shophumm.com.au/content/scripts/price-info.js?productPrice=<?php echo $productPrice ?>&LittleThings&element= <?php echo urlencode($productSelector) ?>"></script>
    <?php else: ?>
        <script src="https://widgets.shophumm.com.au/content/scripts/price-info.js?productPrice=<?php echo $productPrice ?>&BigOnly&element= <?php echo $productSelector ?>"></script>
    <?php endif; ?>
<?php endif; ?>


<?php if ($country == 'NZ'): ?>
    <?php if (!$littleBig) {
        $ec_pattern = sprintf("%s%s%s%s", '<script src= "https://widgets.shophumm.co.nz/content/scripts/price-info.js?productPrice=', $productPrice, '&LittleThings&little=F5', '"></script>');
    }
    echo $ec_pattern;
endif; ?>





